### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by thezell** [Lovsan/Ruutu-Downloader#1]
Moro,

Ei toimi enää jostain syystä..? 

Edit: Sain toimimaan. Jos .m3u8 osoitteessa on merkit -t, niin video ei toistu. Ne poistamalla toimii.

**Comment by spektri** [comment]
Tietämätön kysyy että missä tuo m3u8 sijaitsee

**Comment by thezell** [comment]
> Tietämätön kysyy että missä tuo m3u8 sijaitsee

Sai auki osoitteessa gatling.nelonenmedia.fi..jne mutta kikkakolmonen ei toimi enää.
